package com.example.ReciPage.Model;

public class STEP {
    

public static String c ="cfgdg dgnnfgfffffffffgdg dgnnfgfffffffffgdg dgnnfgfffffffffgdg dgnnfgfffffffffgdg dgnnfgfffffffffgdg dgnnfgfffffffffgdg dgnnfgfffffffffgdg dgnnfgfffffffffgdg dgnnfgfffffffffgdg dgnnfgfffffffffgdg dgnnfgfffffffffgdg dgnnfgfffffffffgdg dgnnfgfffffffffgdg dgnnfgfffffffffgdg dgnnfgfffffffffgdg dgnnfgfffffffffgdg dgnnfgfffffffffgdg dgnnfgfffffffffgdg dgnnfgfffffffffgdg dgnnfgfffffffffgdg dgnnfgfffffffffgdg dgnnfgfffffffffgdg dgnnfgfffffffffgdg dgnnfgfffffffffgdg dgnnfgfffffffffgdg dgnnfgfffffffffgdg dgnnfgfffffffffgdg dgnnfgfffffffffgdg dgnnfgfffffffffgdg dgnnfgfffffffffgdg dgnnfgfffffffffgdg dgnnfgfffffffffgdg dgnnfgfffffffffgdg dgnnfgfffffffffgdg dgnnfgfffffffffgdg dgnnfgfffffffffgdg dgnnfgfffffffffgdg dgnnfgfffffffffgdg dgnnfgfffffffffgdg dgnnfgfffffffffgdg dgnnfgfffffffffgdg dgnnfgfffffffffgdg dgnnfgfffffffffgdg dgnnfgfffffffffgdg dgnnfgfffffffffgdg dgnnfgfffffffffgdg dgnnfgfffffffffgdg dgnnfgfffffffffgdg dgnnfgfffffffffgdg dgnnfgfffffffffgdg dgnnfgfffffffffgdg dgnnfgfffffffffgdg dgnnfgfffffffffgdg dgnnfgfffffffffgdg dgnnfgfffffffffgdg dgnnfgfffffffffgdg dgnnfgfffffffffgdg dgnnfgfffffffffgdg dgnnfgfffffffffgdg dgnnfgfffffffffgdg dgnnfgfffffffffgdg dgnnfgfffffffffgdg dgnnfgfffffffffgdg dgnnfgfffffffffgdg dgnnfgfffffffffgdg dgnnfgfffffffffgdg dgnnfgffffffff";


}
